name: Input Prompt Workflow
on:
  push :
    branches: [master, main]
  pull_request:
    branches: [master, main]
    types: [opened]
jobs:
  input-prompt:
    runs-on: ubuntu-latest
    steps:
      - name: Prompt User for Input
        run: |
          read -p "Have you checked the other platform? (y/n) " yn
          if [[ $yn == "y" ]]; then
            echo "Okay to merge!"
          else
            echo "Please check the other platform before merging."
            exit 1
          fi
