name: Check Before Merge
on:
  pull_request:
    branches:
      - main
jobs:
  check-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Check Platform
        run: |
          # Prompt the user to check a specific platform before merging
          echo "Please check the platform before merging to master."
          read -p "Have you checked the platform? [y/n]: " response
          if [ "$response" = "y" ]; then
            echo "Continuing with merge."
          else
            echo "Aborting merge."
            exit 1
          fi

