name: Check Condition Before Merge
on:
  pull_request:
    branches:
      - master
jobs:
  check-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Check Condition
        run: |
          # Define the numbers to compare
          num1=10
          num2=50

          # Check if num1 is greater than num2
          if [ "$num1" -gt "$num2" ]; then
            echo "Condition met. Continuing with merge."
          else
            echo "Error: Condition not met. Please check before merging to master."
            exit 1
          fi
