name: Pull Request Reminder
on:
  pull_request:
    types: [opened]

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send Reminder
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const prUrl = github.context.payload.pull_request.html_url;

              // Customize the reminder message as needed
              const reminderMessage = `Hi there! Don't forget to review the changes in this pull request before merging. You can view it [here](${prUrl}).`;

              github.issues.createComment({
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                issue_number: github.context.payload.pull_request.number,
                body: reminderMessage
              });
            } catch (error) {
              console.error("Error occurred while posting reminder comment:", error);
            }
